### ISSUE TITLE
Speaker proposal: Publishing node modules

### ISSUE THREAD

**Issue by siddharthkp** [nodeschool/Bengaluru#9]
Title: Publishing your own node module

Abstract: Complete guide for publishing your modules. 

1. Things that you have to know: how to bundle + how to publish, making executable for cli, etc
2. Good practices: descriptive package.json + readme, dependency locking between app vs library, etc. 
3. Optimisations: how do you keep the size small, mention files for prod, etc.

**Comment by somsharan** [comment]
hey sid, thank you for interest in the event, please share your contact info

**Comment by siddharthkp** [comment]
Sent an email to you.
